---
- name: Arch
  hosts: localhost
  connection: local
  vars_prompt:
    - name: "flavour"
      prompt: "Which preset do you want? Enter [sarah/luzey]"
      private: no
  tasks:
    - set_fact:
        flavour: '{{ flavour }}'

    - name: Install and update packages
      become: yes
      import_tasks: 'playbooks/1-install/system.yml'

    - name: Apply some system tweaks
      become: yes
      import_tasks: 'playbooks/1-install/tweaks.yml'

    - name: Import Lucys preset if chosen
      become: yes
      import_tasks: 'playbooks/2-flavours/luzey.yml'
      when: flavour|string == "luzey"

    - name: Import Sarahs preset if chosen
      become: yes
      import_tasks: 'playbooks/2-flavours/sarah.yml'
      when: flavour|string == "sarah"
