---
- name: Arch
  hosts: localhost
  connection: local
  gather_facts: yes
  become: false
  vars_prompt:
     - name: 'user_password'
       prompt: 'Enter user password'
       private: true
       encrypt: sha512_crypt
       confirm: true
       salt_size: 7
  tasks:
     - name: Determine Distro
       debug: msg="{{ ansible_distribution }}"

     - name: Install and update packages
       become: true
       import_tasks: 'playbooks/1-install/system.yml'

     - name: Install and update system packages
       become: true
