---
- name: Arch
  hosts: localhost
  connection: local
  vars_prompt:
     - name: 'user_password'
       prompt: 'Enter user password'
       private: true
       encrypt: sha512_crypt
       confirm: true
       salt_size: 7
  tasks:
     - name: Install and update packages
       become: yes
       import_tasks: 'playbooks/1-install/system.yml'
     - name: Change some settings
       become: yes
       import_tasks: 'playbooks/1-install/config.yml'
