---
basic_packages:
   - btop
   - neofetch
   - unrar
   - unarchiver
   - unace
   - xz
   - udisks2
   - jshon
   - expac
   - wget
   - acpid
   - net-tools
   - xdg-user-dirs
   - xf86-input-synaptics
   - xf86-input-libinput
   - xf86-input-evdev
   - mesa
   - lib32-mesa
   - vulkan-icd-loader
   - lib32-vulkan-icd-loader
   - alsa-utils
   - pipewire
   - pipewire-pulse
   - pipewire-jack
   - wireplumber
   - ntfs-3g
