---
# kewl stuff :p

- name: Add flavour-based variables
  include_vars:
    file: '../pkgs/flav_luzey.yml'

- name: Install yay packages
  kewlfft.aur.aur:
    use: yay
    name: '{{ yay_packages }}'
    state: present

- name: Enable services
  service:
     name: '{{ services }}'
     enabled: yes

- name: Get supported version
  shell: /lib/ld-linux-x86-64.so.2 --help | grep -m 1 "supported" | awk '{match($0, /[a-z0-9-]+/); print substr($0, RSTART, RLENGTH)}'
  register: packageversions

# TODO: ...
#- name: Install EEDVF Kernel
#  become: yes
