- name: Enable CachyOs repo
  shell: |
     pacman-key --recv-keys F3B607488DB35A47 --keyserver keyserver.ubuntu.com
     pacman-key --lsign-key F3B607488DB35A47
     pacman --needed --noconfirm -U \
      'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-keyring-20240331-1-any.pkg.tar.zst' \
      'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-mirrorlist-18-1-any.pkg.tar.zst' \
      'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-v3-mirrorlist-18-1-any.pkg.tar.zst' \
      'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-v4-mirrorlist-6-1-any.pkg.tar.zst' \
      'https://mirror.cachyos.org/repo/x86_64/cachyos/pacman-6.1.0-5-x86_64.pkg.tar.zst'
 
- name: Full system upgrade
  pacman:
     update_cache: true
     upgrade: true
 
- name: Install base-devel and git
  pacman:
    name:
      - base-devel
      - git
    state: present
    reason: explicit
    reason_for: all
 
- name: Include basic package list
  include_vars:
     file: '../pkgs/system.yaml'
 
- name: Install Basic Packages
  pacman:
    name: '{{ basic_packages }}'
    state: present
    reason: explicit
    reason_for: all
 
- name: Check GPU Vendor
  shell: lspci | grep -i VGA | awk '!/NVIDIA|AMD|Intel/'
  register: gpu_info
 
- name: Include GPU vendor-specific package list
  include_vars:
     file: '../pkgs/system_gpu.yaml'

- name: Set GPU Vendor Facts
  set_fact:
     gpu_vendor: >-
        {{ ('NVIDIA' if 'NVIDIA' in gpu_info.stdout else
           'Intel' if 'Intel' in gpu_info.stdout else
           'AMD' if 'AMD' in gpu_info.stdout else
           'Unknown') | trim }}
     gpu_packages: {'AMD': '{{ amd_packages }}', 'NVIDIA': '{{ nvidia_packages }}', 'Intel': '{{ intel_packages }}'}

- name: Install GPU Drivers
  pacman:
    name: '{{ gpu_packages[gpu_vendor] }}'
    state: present
    reason: explicit
    reason_for: all
  when: gpu_vendor|string != "Unknown"
