- name: All hosts up-to-date
  hosts: control managed
  become: true

  tasks:
     - name: Enable CachyOs repo
       shell: 'cd /tmp/ ; curl -O https://mirror.cachyos.org/cachyos-repo.tar.xz && tar xvf cachyos-repo.tar.xz ; cd cachyos-repo ; chmod +x ./cachyos-repo.sh && ./cachyos-repo.sh'

     - name: Full system upgrade
       community.general.pacman:
          update_cache: true
          upgrade: true

    - name: Install Yay
      shell: 'cd /tmp/ ; git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -rsi'

     - name: Install basic packages
       community.general.pacman:
          name: { { item } }
          state: present
       with_items:
          - p7zip
          - pfetch
          - unrar
          - unarchiver
          - unace
          - xz
          - udisks2
          - jshon
          - expac
          - git
          - wget
          - acpid
          - net-tools
          - xdg-user-dirs
          - xf86-input-synaptics
          - xf86-input-libinput
          - xf86-input-evdev
          - mesa
          - lib32-mesa
          - vulkan-icd-loader
          - lib32-vulkan-icd-loader
          - alsa-utils
          - pipewire
          - pipewire-pulse
          - pipewire-jack
          - wireplumber

     - name: Check if HDD or SSD
       shell: cat "/sys/block/{{ satellite_physical_disk }}/queue/rotational"
       register: is_ssd

     - name: Enable fstrim if SSD is found
       command: 'fstrim -av'
       when: is_ssd.stdout|int == 0

     - name: Determine Hardware for further installation
